project_id = "vgkmcerjlwnzbiukinhd"

[functions.conecta-chat-webhook]
verify_jwt = false

[functions.create-client-with-portal]
verify_jwt = true

[functions.create-team-user]
verify_jwt = true

[functions.reset-client-portal-passwords]
verify_jwt = true

[functions.ensure-client-portal-profile]
verify_jwt = true

[functions.create-admin]
verify_jwt = true

[functions.send-newsletter-broadcast]
verify_jwt = true

[functions.email-inbox-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.manage-team-user]
verify_jwt = true

[functions.acessorias-module]
verify_jwt = true

[functions.manage-integration-token]
verify_jwt = true

[functions.grow-assistant]
verify_jwt = true

[functions.grow-assistant-confirm-action]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false
