import { AlertTriangle, CheckCircle2, Clock3, Download, FileCheck2, Mail, RefreshCw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { Alert,AlertDescription } from "@/components/ui/alert";
import { useClientFiscalStatus } from "@/features/integra-contador/hooks/useClientFiscalStatus";
import { useClientCnd } from "@/features/integra-contador/hooks/useClientCnd";
const activeStatuses=new Set(["queued","processing","waiting_external"]);
const statusLabels:Record<string,string>={queued:"Na fila",processing:"Consultando",waiting_external:"Aguardando Receita",completed:"Consulta concluída",requires_action:"Requer ação",failed:"Falhou"};
export function ClientFiscalStatusSection({organizationId,clientId,enabled}:{organizationId:string;clientId:string;enabled:boolean}){
  const {query,sync}=useClientFiscalStatus(organizationId,clientId,enabled);
  const cnd=useClientCnd(organizationId,clientId,enabled);
  if(!enabled)return null;
  const status=query.data;const updating=activeStatuses.has(status?.run?.status||"");const hasNewMessages=Boolean(status?.indicator?.hasNewMessages);const runStatus=status?.run?.status;
  const handleConsult=()=>sync.mutate(true,{onSuccess:()=>toast.success("Consulta fiscal iniciada. O resultado será atualizado automaticamente."),onError:()=>toast.error("Não foi possível iniciar a consulta fiscal.")});
  const handleIssueCnd=()=>cnd.issue.mutate(undefined,{onSuccess:(certificate)=>{if(certificate.status==="valid")toast.success("CND obtida com sucesso.");else if(certificate.status==="not_issued")toast.error("A certidão não pôde ser emitida.",{description:certificate.provider_message||undefined});else toast.info("A consulta da CND ainda está em processamento.");},onError:(error)=>toast.error(error instanceof Error&&error.message==="CND_CONTRACT_NOT_CONFIGURED"?"Configure as credenciais da API Consulta CND no SERPRO.":"Não foi possível consultar ou emitir a CND.")});
  const certificate=cnd.query.data?.certificate;
  return <Card aria-labelledby="fiscal-status-title"><CardHeader className="space-y-2"><div className="flex flex-wrap items-start justify-between gap-3"><div className="space-y-1"><CardTitle id="fiscal-status-title" className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/>Situação fiscal do cliente</CardTitle><CardDescription>Consulte a integração fiscal para identificar mensagens e revisões que exigem acompanhamento interno.</CardDescription></div>{runStatus?<Badge variant={runStatus==="completed"?"secondary":runStatus==="requires_action"?"destructive":"outline"}>{statusLabels[runStatus]||runStatus}</Badge>:null}</div></CardHeader><CardContent className="space-y-4">
    {query.isLoading?<p role="status" className="flex items-center gap-2 text-sm text-muted-foreground"><RefreshCw className="h-4 w-4 animate-spin"/>Carregando a última situação fiscal…</p>:null}
    {query.isError?<Alert variant="destructive"><AlertDescription>Não foi possível carregar a situação fiscal. Os demais dados do cliente continuam disponíveis.</AlertDescription></Alert>:null}
    {status?.indicator?<div role="status" aria-live="polite" className="flex items-start gap-3 rounded-lg border bg-muted/20 p-4">{hasNewMessages?<AlertTriangle className="mt-0.5 h-5 w-5 text-amber-600"/>:<CheckCircle2 className="mt-0.5 h-5 w-5 text-emerald-600"/>}<div className="space-y-1"><p className="font-medium">{hasNewMessages?"Há novas mensagens na Caixa Postal":"Nenhuma nova mensagem identificada"}</p><p className="text-xs text-muted-foreground">Atualizado em {new Date(status.indicator.fetchedAt).toLocaleString("pt-BR")}{status.indicator.stale?" · resultado desatualizado":""}</p></div></div>:!query.isLoading&&!query.isError?<div className="flex items-start gap-3 rounded-lg border border-dashed p-4"><Mail className="mt-0.5 h-5 w-5 text-muted-foreground"/><div><p className="text-sm font-medium">Nenhuma consulta realizada</p><p className="text-xs text-muted-foreground">Use o botão abaixo para buscar a situação fiscal disponível na integração.</p></div></div>:null}
    {status?.run?.status==="requires_action"?<Alert variant="destructive"><AlertDescription>É necessário regularizar a procuração, o certificado ou a configuração da integração antes de consultar novamente{status.run.errorCode?` (${status.run.errorCode})`:""}.</AlertDescription></Alert>:null}
    {status?.reviews?.map(review=><Alert key={review.id}><AlertDescription><strong>Revisão fiscal: </strong>{review.recommendedAction}<span className="ml-2 text-xs text-muted-foreground">({review.status})</span></AlertDescription></Alert>)}
    {updating?<p role="status" aria-live="polite" className="flex items-center gap-2 text-sm text-muted-foreground"><Clock3 className="h-4 w-4"/>{runStatus==="waiting_external"?"Aguardando retorno da Receita…":"Consulta em processamento…"}</p>:null}
    <div className="flex flex-wrap items-center gap-3"><Button type="button" disabled={sync.isPending||updating} onClick={handleConsult} aria-label="Consultar situação fiscal do cliente"><RefreshCw className={`mr-2 h-4 w-4 ${sync.isPending||updating?"animate-spin":""}`}/>{updating?"Consultando…":"Consultar situação fiscal"}</Button><p className="max-w-2xl text-xs text-muted-foreground">A consulta é interna e não cria nem envia uma pendência ao portal do cliente.</p></div>
    <div className="space-y-3 rounded-lg border bg-muted/10 p-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 font-medium"><FileCheck2 className="h-4 w-4"/>Certidão Negativa de Débitos Federal</p><p className="text-xs text-muted-foreground">Consulta uma certidão válida ou solicita uma nova à API Consulta CND do SERPRO.</p></div>{certificate?<Badge variant={certificate.status==="valid"?"secondary":certificate.status==="not_issued"?"destructive":"outline"}>{certificate.status==="valid"?"Válida":certificate.status==="not_issued"?"Não emitida":certificate.status==="processing"?"Processando":"Falhou"}</Badge>:null}</div>
      {certificate?.status==="valid"?<div className="grid gap-2 text-xs text-muted-foreground sm:grid-cols-3"><span>Controle: <strong className="text-foreground">{certificate.control_code}</strong></span><span>Emissão: <strong className="text-foreground">{certificate.issued_at?new Date(certificate.issued_at).toLocaleDateString("pt-BR"):"—"}</strong></span><span>Validade: <strong className="text-foreground">{certificate.valid_until?new Date(`${certificate.valid_until}T12:00:00`).toLocaleDateString("pt-BR"):"—"}</strong></span></div>:null}
      {certificate?.status==="not_issued"?<Alert variant="destructive"><AlertDescription>{certificate.provider_message||"A Receita Federal não emitiu a certidão para este contribuinte."}</AlertDescription></Alert>:null}
      {cnd.query.data&&!cnd.query.data.configured?<Alert><AlertDescription>A função está pronta, mas as credenciais específicas da API Consulta CND ainda não foram configuradas.</AlertDescription></Alert>:null}
      <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={cnd.issue.isPending||cnd.query.isLoading||cnd.query.data?.configured===false} onClick={handleIssueCnd}><FileCheck2 className={`mr-2 h-4 w-4 ${cnd.issue.isPending?"animate-pulse":""}`}/>{cnd.issue.isPending?"Consultando CND…":"Gerar CND"}</Button>{certificate?.status==="valid"&&certificate.storage_path?<Button type="button" variant="ghost" onClick={()=>void cnd.openPdf(certificate.id).catch(()=>toast.error("Não foi possível abrir o PDF da CND."))}><Download className="mr-2 h-4 w-4"/>Baixar PDF</Button>:null}</div>
    </div>
  </CardContent></Card>;
}
