import { useDeferredValue, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Loader2, RefreshCw, Search, ServerCog } from "lucide-react";
import { AppLayout } from "@/components/app/AppLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";

type Source = "nfe_sefaz" | "nfse_adn";
type Client = { id: string; name: string; cnpj: string | null; status: string | null };
type SyncState = { id: string; client_id: string; source: Source; last_nsu: number; max_nsu: number | null; status: string; last_success_at: string | null; last_error_code: string | null; next_allowed_at: string | null };
type Overview = { clients: Client[]; states: SyncState[]; totals: { count: number; amount: number; nfe_sefaz: number; nfse_adn: number }; runs: Array<{ id: string; client_id: string; source: Source; status: string; documents_received: number; documents_changed: number; created_at: string; error_code: string | null }> };
type Invoice = { id: string; client_id: string; source: Source; nsu: number | null; access_key: string; document_model: string; document_number: string | null; direction: string; status: string; issued_at: string | null; issuer_name: string | null; recipient_name: string | null; total_amount: number | null };
const sourceLabels: Record<Source, string> = { nfe_sefaz: "NF-e Produtos", nfse_adn: "NFS-e Serviços" };
const errorLabels: Record<string, string> = { certificate_required: "Cadastre o certificado A1 deste cliente.", certificate_expired: "O certificado A1 está vencido.", certificate_invalid: "O arquivo A1 não contém um certificado e uma chave privada válidos.", certificate_key_mismatch: "O certificado do arquivo A1 não corresponde à chave privada. Cadastre novamente o A1 correto.", client_cnpj_required: "O cliente precisa ter um CNPJ válido.", sync_rate_limited: "A fonte fiscal exige aguardar antes da próxima consulta.", nfe_rate_limited: "A SEFAZ bloqueou temporariamente novas consultas por consumo indevido.", certificate_vault_not_configured: "O cofre de certificados ainda não foi configurado no servidor." };

async function invokeInvoices<T>(body: Record<string, unknown>) {
  const { data, error } = await supabase.functions.invoke<T & { error?: { code?: string } }>("fiscal-invoices-module", { body });
  if (error) { let code = "operation_failed"; const context = (error as { context?: Response }).context; if (context) { const payload = await context.clone().json().catch(() => null) as { error?: { code?: string } } | null; code = payload?.error?.code || code; } throw new Error(code); }
  if (data?.error?.code) throw new Error(data.error.code); return data;
}
function money(value: number | null | undefined) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value || 0)); }
function shortDate(value: string | null) { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value)) : "—"; }
function statusLabel(status: string) { return ({ idle: "Pendente", queued: "Na fila", syncing: "Sincronizando", up_to_date: "Atualizado", requires_action: "Requer ação", failed: "Falhou" } as Record<string, string>)[status] || status; }

export default function FiscalInvoicesPage() {
  const { currentOrganizationId } = useAuth(); const queryClient = useQueryClient();
  const [clientFilter, setClientFilter] = useState("all"), [sourceFilter, setSourceFilter] = useState("all"), [directionFilter, setDirectionFilter] = useState("all"), [search, setSearch] = useState("");
  const deferredSearch = useDeferredValue(search.trim()); const overviewKey = ["fiscal-invoices-overview", currentOrganizationId] as const;
  const overviewQuery = useQuery({ queryKey: overviewKey, enabled: Boolean(currentOrganizationId), queryFn: () => invokeInvoices<Overview>({ action: "overview", organizationId: currentOrganizationId }) });
  const listQuery = useQuery({ queryKey: ["fiscal-invoices", currentOrganizationId, clientFilter, sourceFilter, directionFilter, deferredSearch], enabled: Boolean(currentOrganizationId), queryFn: () => invokeInvoices<{ invoices: Invoice[]; count: number }>({ action: "list", organizationId: currentOrganizationId, clientId: clientFilter === "all" ? undefined : clientFilter, source: sourceFilter === "all" ? undefined : sourceFilter, direction: directionFilter === "all" ? undefined : directionFilter, search: deferredSearch || undefined, limit: 100 }) });
  const syncMutation = useMutation({ mutationFn: ({ clientId, source }: { clientId: string; source: Source }) => invokeInvoices<{ changed: number; received: number }>({ action: "sync", organizationId: currentOrganizationId, clientId, source, environment: "production" }), onSuccess: async (result) => { toast.success(`${result.changed} documento(s) novo(s) ou atualizado(s).`); await Promise.all([queryClient.invalidateQueries({ queryKey: overviewKey }), queryClient.invalidateQueries({ queryKey: ["fiscal-invoices", currentOrganizationId] })]); }, onError: (cause) => toast.error(errorLabels[(cause as Error).message] || "Não foi possível consultar a fonte fiscal.") });
  const overview = overviewQuery.data; const clientById = new Map((overview?.clients || []).map((client) => [client.id, client])); const stateByClientSource = new Map((overview?.states || []).map((state) => [`${state.client_id}:${state.source}`, state]));

  return <AppLayout><div className="mx-auto max-w-7xl space-y-6"><div><Badge variant="outline" className="mb-3 gap-1.5"><ServerCog className="h-3.5 w-3.5" /> Distribuição fiscal nacional</Badge><h1 className="font-heading text-3xl font-bold tracking-tight">Notas Fiscais</h1><p className="mt-1 text-sm text-muted-foreground">Consulta de NF-e de produtos na SEFAZ e NFS-e de serviços no ADN Nacional.</p></div>
    <dl className="flex flex-wrap gap-x-8 gap-y-3 border-y py-3" aria-label="Resumo das notas fiscais">{[["Documentos", String(overview?.totals.count || 0)], ["Valor identificado", money(overview?.totals.amount)], ["NF-e produtos", String(overview?.totals.nfe_sefaz || 0)], ["NFS-e serviços", String(overview?.totals.nfse_adn || 0)]].map(([label, value]) => <div key={label} className="flex items-baseline gap-2"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="text-sm font-semibold tabular-nums">{value}</dd></div>)}</dl>
    <Tabs defaultValue="documents" className="space-y-4"><TabsList className="grid h-auto w-full grid-cols-2 rounded-2xl bg-muted/60 p-1"><TabsTrigger value="documents" className="h-10 rounded-xl">Documentos</TabsTrigger><TabsTrigger value="sync" className="h-10 rounded-xl">Sincronização por cliente</TabsTrigger></TabsList>
      <TabsContent value="documents" className="space-y-4"><div className="grid gap-3 rounded-2xl border bg-card p-4 md:grid-cols-[1fr_190px_190px_190px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Chave, emitente ou destinatário" className="pl-9" /></div><Select value={clientFilter} onValueChange={setClientFilter}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todos os clientes</SelectItem>{overview?.clients.map((client) => <SelectItem key={client.id} value={client.id}>{client.name}</SelectItem>)}</SelectContent></Select><Select value={sourceFilter} onValueChange={setSourceFilter}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todas as fontes</SelectItem><SelectItem value="nfe_sefaz">NF-e Produtos</SelectItem><SelectItem value="nfse_adn">NFS-e Serviços</SelectItem></SelectContent></Select><Select value={directionFilter} onValueChange={setDirectionFilter}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Entradas e saídas</SelectItem><SelectItem value="received">Recebidas</SelectItem><SelectItem value="issued">Emitidas</SelectItem></SelectContent></Select></div>
        <div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="border-b bg-muted/30 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Documento</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Origem</th><th className="px-4 py-3">Participantes</th><th className="px-4 py-3">Emissão</th><th className="px-4 py-3 text-right">Valor</th></tr></thead><tbody>{listQuery.isLoading ? <tr><td colSpan={6} className="py-16 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-muted-foreground" /></td></tr> : (listQuery.data?.invoices || []).length === 0 ? <tr><td colSpan={6} className="py-16 text-center text-muted-foreground">Nenhuma nota encontrada. Inicie uma sincronização por cliente.</td></tr> : listQuery.data?.invoices.map((invoice) => <tr key={invoice.id} className="border-b last:border-0"><td className="px-4 py-3"><p className="font-medium">{invoice.document_model} {invoice.document_number ? `nº ${invoice.document_number}` : ""}</p><p className="max-w-48 truncate font-mono text-[11px] text-muted-foreground" title={invoice.access_key}>{invoice.access_key}</p></td><td className="px-4 py-3">{clientById.get(invoice.client_id)?.name || "Cliente"}</td><td className="px-4 py-3"><Badge variant="secondary">{sourceLabels[invoice.source]}</Badge><p className="mt-1 text-xs text-muted-foreground">{invoice.direction === "received" ? "Recebida" : invoice.direction === "issued" ? "Emitida" : "Não definida"}</p></td><td className="px-4 py-3"><p className="max-w-56 truncate">{invoice.issuer_name || "Emitente não informado"}</p><p className="max-w-56 truncate text-xs text-muted-foreground">Para: {invoice.recipient_name || "não informado"}</p></td><td className="px-4 py-3">{shortDate(invoice.issued_at)}</td><td className="px-4 py-3 text-right font-medium">{money(invoice.total_amount)}</td></tr>)}</tbody></table></div></div></TabsContent>
      <TabsContent value="sync" className="space-y-3">{overviewQuery.isLoading ? <div className="flex min-h-48 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin" /></div> : overview?.clients.map((client) => <div key={client.id} className="rounded-2xl border bg-card p-4 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold">{client.name}</p><p className="text-xs text-muted-foreground">{client.cnpj || "CNPJ não informado"}</p></div><div className="grid gap-3 sm:grid-cols-2">{(["nfe_sefaz", "nfse_adn"] as Source[]).map((source) => { const state = stateByClientSource.get(`${client.id}:${source}`); const waiting = state?.next_allowed_at && new Date(state.next_allowed_at) > new Date(); return <div key={source} className="min-w-72 rounded-xl border bg-muted/20 p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-medium">{sourceLabels[source]}</p><p className="text-xs text-muted-foreground">NSU {state?.last_nsu || 0} · {statusLabel(state?.status || "idle")}</p></div><Button size="sm" variant="outline" disabled={syncMutation.isPending || Boolean(waiting)} onClick={() => syncMutation.mutate({ clientId: client.id, source })}>{syncMutation.isPending && syncMutation.variables?.clientId === client.id && syncMutation.variables.source === source ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}<span className="sr-only">Sincronizar {sourceLabels[source]}</span></Button></div>{state?.last_error_code ? <p className="mt-2 flex gap-1 text-xs text-destructive"><AlertTriangle className="h-3.5 w-3.5 shrink-0" />{errorLabels[state.last_error_code] || state.last_error_code}</p> : null}</div>; })}</div></div></div>)}</TabsContent>
    </Tabs></div></AppLayout>;
}
