import { AppLayout } from "@/components/app/AppLayout";
import { InstallmentsSection } from "@/features/integra-contador/components/InstallmentsSection";
import { ConnectionSettingsForm } from "@/features/integra-contador/components/ConnectionSettingsForm";
import { ConnectionHealthCard } from "@/features/integra-contador/components/ConnectionHealthCard";
import { useIntegraContadorConnection } from "@/features/integra-contador/hooks/useIntegraContadorConnection";
import { useAuth } from "@/hooks/useAuth";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

export default function InstallmentsPage(){const {currentOrganizationId,effectiveAccess}=useAuth();const connection=useIntegraContadorConnection(currentOrganizationId);const status=connection.statusQuery.data?.status||"não configurada";return <AppLayout><main className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="font-heading text-3xl font-bold tracking-tight">Parcelamentos</h1><p className="mt-1 text-sm text-muted-foreground">Acompanhamento dos acordos do Simples Nacional e MEI consultados no SERPRO.</p></div><Badge variant={status==="active"?"secondary":"outline"}>Conexão: {status}</Badge></header>{currentOrganizationId?<><InstallmentsSection organizationId={currentOrganizationId}/>{effectiveAccess?.primaryRole==="admin"?<Accordion type="single" collapsible className="border-t"><AccordionItem value="connection" className="border-b-0"><AccordionTrigger>Configuração segura da conexão SERPRO</AccordionTrigger><AccordionContent className="space-y-4"><ConnectionHealthCard connection={connection.statusQuery.data??null} canTest testing={connection.testMutation.isPending} onTest={()=>connection.testMutation.mutate()}/><ConnectionSettingsForm organizationId={currentOrganizationId} submitting={connection.configureMutation.isPending} onSubmit={(input)=>connection.configureMutation.mutateAsync(input).then(()=>undefined)}/></AccordionContent></AccordionItem></Accordion>:null}</>:<p className="text-sm text-muted-foreground">Selecione uma organização.</p>}</main></AppLayout>;}
