-- Obligation instances are already projected directly in the calendar.
-- Remove the legacy duplicated calendar rows generated by the obligations module.
delete from public.calendar_events
where integration_source = 'grow_obligation';
