// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_SUPABASE_URL = "https://invalid.supabase.local";
const FALLBACK_PUBLISHABLE_KEY = "sb_publishable_missing_configuration";

function normalizeEnvValue(value: unknown) {
  if (typeof value !== "string") return null;
  const normalized = value.trim().replace(/^['"]|['"]$/g, "");
  if (!normalized) return null;
  if (normalized.includes("your-project-id")) return null;
  if (normalized.includes("xxxxxxxx")) return null;
  return normalized;
}

function readSupabaseEnv() {
  // Vite replaces these statically at build time; avoid dynamic key access.
  const supabaseUrl = normalizeEnvValue(import.meta.env.VITE_SUPABASE_URL);
  const supabaseProjectId = normalizeEnvValue(import.meta.env.VITE_SUPABASE_PROJECT_ID);
  const publishableKey = normalizeEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

  const resolvedUrl = supabaseUrl ?? (supabaseProjectId ? `https://${supabaseProjectId}.supabase.co` : null);
  return { resolvedUrl, publishableKey };
}

function resolveSupabaseConfig() {
  const { resolvedUrl, publishableKey } = readSupabaseEnv();
  const isConfigured = Boolean(resolvedUrl && publishableKey);

  if (!isConfigured) {
    console.error(
      "[supabase] Configuracao ausente: defina VITE_SUPABASE_PUBLISHABLE_KEY e VITE_SUPABASE_URL ou VITE_SUPABASE_PROJECT_ID. O app carregou em modo restrito."
    );
  }

  return {
    url: resolvedUrl ?? FALLBACK_SUPABASE_URL,
    publishableKey: publishableKey ?? FALLBACK_PUBLISHABLE_KEY,
    isConfigured,
  };
}

const supabaseConfig = resolveSupabaseConfig();
const SUPABASE_URL = supabaseConfig.url;
const SUPABASE_PUBLISHABLE_KEY = supabaseConfig.publishableKey;
export const isSupabaseConfigured = supabaseConfig.isConfigured;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
