// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function normalizeEnvValue(value: unknown) {
  if (typeof value !== "string") return null;
  const normalized = value.trim().replace(/^['"]|['"]$/g, "");
  if (!normalized) return null;
  if (normalized.includes("your-project-id")) return null;
  if (normalized.includes("xxxxxxxx")) return null;
  return normalized;
}

function readSupabaseEnv() {
  // Vite replaces these statically at build time; avoid dynamic key access.
  const supabaseUrl = normalizeEnvValue(import.meta.env.VITE_SUPABASE_URL);
  const supabaseProjectId = normalizeEnvValue(import.meta.env.VITE_SUPABASE_PROJECT_ID);
  const publishableKey = normalizeEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

  const resolvedUrl = supabaseUrl ?? (supabaseProjectId ? `https://${supabaseProjectId}.supabase.co` : null);
  return { resolvedUrl, publishableKey };
}

function getRequiredEnv(name: "VITE_SUPABASE_URL" | "VITE_SUPABASE_PUBLISHABLE_KEY", value: string | null) {
  if (!value) {
    throw new Error(`[supabase] Variavel obrigatoria ausente: ${name}`);
  }
  return value;
}

const { resolvedUrl, publishableKey } = readSupabaseEnv();
const SUPABASE_URL = getRequiredEnv("VITE_SUPABASE_URL", resolvedUrl);
const SUPABASE_PUBLISHABLE_KEY = getRequiredEnv("VITE_SUPABASE_PUBLISHABLE_KEY", publishableKey);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
